### ISSUE TITLE
Skin tone mismatch issue

### ISSUE THREAD

**Issue by nelsontseng0704** [Elsaam2y/DINet_optimized#5]
Hi Guys, thanks for the optimized version and docker file. Really save me a lot of time to play around.
I have generate few examples with different skin tone of people. I found out people with lighter skin may have[ skin tone mismatch](https://ibb.co/ThfY3q5).

Well... I am thinking solution for this:

1. retrain the model with bigger and more balance datasets
2. use gfpgan cpp version to fix the issue, but not a guarantee solution

Any idea to tackle skin tone mismatch issue??

Thanks,

**Comment by Inferencer** [comment]
> Hi Guys, thanks for the optimized version and docker file. Really save me a lot of time to play around. I have generate few examples with different skin tone of people. I found out people with lighter skin may have[ skin tone mismatch](https://ibb.co/ThfY3q5).
> 
> Well... I am thinking solution for this:
> 
>     1. retrain the model with bigger and more balance datasets
> 
>     2. use gfpgan cpp version to fix the issue, but not a guarantee solution
> 
> 
> Any idea to tackle skin tone mismatch issue??
> 
> Thanks,

I know certain video editing apps such as DaVinci offer simply one-click solutions to this issue, considering you should be using them to mask anyways it might be worth looking at shot matching although I don't know what other app with this feature reffer to it as

**Comment by Elsaam2y** [comment]
Thanks @nelsontseng0704. Yes it is a problem with any identities not similar to the distribution of the dataset. As you mentioned, training on a bigger dataset should be a valid solution. But how big and diverse the dataset should be, still unanswered question and needs some experimentation. 

@nelsontseng0704 @Inferencer I believe gfpgan might not help that much here. The output could became even worse in this case since the model will apply super-resolution regardless of any color mismatch. 

What I was thinking of is to apply color histogram or color transfer to let the mask learn the color distribution from either the surrounding area of the face, or better the original frame. I have to say this could be a bit challenging, but I think it is worth investigation. It won’t also add any significant latency to the overall processing.

**Comment by Elsaam2y** [comment]
Feel free to reopen for any further questions.
